version: '3.8'
services:
    php8-sf6:
        container_name: ${CONTAINER_NAME}
        image: ${IMAGE_NAME}

        ports:
            - ${PORT_HOST}:8000
        volumes:
            - ${PATH_PROJECT}:/var/www/html