version: '3.8'
services:
    php8-sf6:
        env_file:
            - .env
        container_name: ${CONTAINER_NAME}
        build: 
            context: ./php-symfony
            dockerfile: Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION}
        image: ${IMAGE_NAME}
        ports:
            - ${PORT_HOST}:8000
        volumes:
            - ${PATH_PROJECT}:/var/www/html
        networks:
            - php-symfony-networks

networks:
    php-symfony-networks:
        name: networks-${CONTAINER_NAME}