# Path: ./docker-compose.from-image.yml
#
# Used when the image is already built
#
# This project is available on github : https://github.com/mathurinhauville/symfony-php-custom-docker
# @Author : https://github.com/mathurinhauville

version: '3.8'
services:
    php8-sf6:
        container_name: ${CONTAINER_NAME}
        image: ${IMAGE_NAME}
        networks:
            - php-symfony-networks
        ports:
            - ${PORT_HOST}:8000
        volumes:
            - ${PATH_PROJECT}:/var/www/html

networks:
    php-symfony-networks:
        name: networks-${CONTAINER_NAME}