# Path: ./docker-compose.yml
#
# Create new image and new container from .env file
#
# This project is available on github : https://github.com/mathurinhauville/symfony-php-custom-docker
# @Author : https://github.com/mathurinhauville

version: '3.8'
services:
    php8-sf6:
        env_file:
            - .env
        container_name: ${PROJECT_NAME}-symfony${SYMFONY_VERSION}-php${PHP_VERSION}
        build: 
            context: ./bin
            dockerfile: Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION}
        image: symfony/php${PHP_VERSION}:latest
        ports:
            - ${PORT_HOST}:8000
        volumes:
            - ${PATH_CURRENT_PROJECT}:/var/www/html
        networks:
            - php-symfony-networks

networks:
    php-symfony-networks:
        name: networks-${PROJECT_NAME}-symfony${SYMFONY_VERSION}-php${PHP_VERSION}