version: '3.8'
services:
    php8-sf6:
        container_name: ${PROJECT_NAME}-symfony${SYMFONY_VERSION}-php${PHP_VERSION}
        build: 
            context: ./php-symfony
            dockerfile: Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION}
        image: symfony/php${PHP_VERSION}:latest
        networks:
            - php-symfony-networks
        ports:
            - ${PORT_HOST}:8000
        volumes:
            - ./:/var/www/html
        
networks:
    php-symfony-networks:
        name: networks-${PROJECT_NAME}-symfony${SYMFONY_VERSION}-php${PHP_VERSION}
