version: '3.8'
services:
    php8-sf6:
        container_name: ${CONTAINER_NAME}
        build: 
            context: ./php-symfony
            dockerfile: Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION}
                GIT_NAME: ${GIT_NAME}
                GIT_EMAIL: ${GIT_EMAIL}
        image: ${IMAGE_NAME}
        networks:
            - php-symfony-networks
        ports:
            - ${PORT_HOST}:8000
        volumes:
            - ../:/var/www/html
        
networks:
    php-symfony-networks:
        name: networks-${CONTAINER_NAME}
