name: Reset env

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  reset-env:
    runs-on: ubuntu-latest

    steps:
    - name: make
      run: ../../scripts/reset-env.sh 
